# Generated by Django 5.1.2 on 2024-11-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='content',
            field=models.TextField(default='Error'),
        ),
    ]
