# Generated by Django 5.1.2 on 2024-10-30 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_categories_product_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Покупатель'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Покупатель'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.IntegerField(blank=True)),
                ('tg_username', models.CharField(blank=True, max_length=20, verbose_name='Telegram Username')),
                ('name', models.CharField(blank=True, max_length=20, verbose_name='Имя')),
                ('balance', models.FloatField(default=0, verbose_name='Баланс')),
                ('date_of_registration', models.DateField(auto_now_add=True)),
                ('payments', models.ManyToManyField(blank=True, related_name='payments', to='shop.payment', verbose_name='Платежи')),
                ('sales', models.ManyToManyField(blank=True, related_name='sales', to='shop.sale', verbose_name='Покупки')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
