# Generated by Django 5.1.2 on 2024-10-30 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_payment_customer_alter_sale_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='tg_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tg_username',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telegram Username'),
        ),
    ]
