# Generated by Django 5.1.2 on 2024-11-05 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_userprofile_tg_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='Баланс'),
        ),
    ]
