# Generated by Django 5.1.2 on 2024-11-05 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_userprofile_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='successful_payment_answer',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='is_counted',
            new_name='is_multiple',
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_unlimited', models.BooleanField(default=False, verbose_name='Бесконечный')),
                ('data', models.TextField(verbose_name='Содержимое')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='shop.product')),
            ],
            options={
                'verbose_name': 'Содержимое',
                'verbose_name_plural': 'Содержимое',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='content',
            field=models.ManyToManyField(related_name='answer', to='shop.content', verbose_name='После оплаты'),
        ),
        migrations.DeleteModel(
            name='Good',
        ),
    ]
