# Generated by Django 5.1.2 on 2024-11-05 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_product_successful_payment_answer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cost',
            new_name='price',
        ),
    ]
